import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout'
import Link from 'next/link'
import utilStyles from '../styles/utils.module.css'

const name = 'Jeppe Løvstad'

const me = () => (

  <Image
    src="/images/SWC_small.jpg"
    height={400}
    width={400}
    alt="Jeppe Løvstad"
  />

)

const Home: NextPage = () => {
  return (

    <Layout me>
      <Head>
        <title>Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        priority
        src="/images/SWC_small.jpg"
        className={utilStyles.borderCircle}
        height={144}
        width={144}
        alt={name}
      />
      <h1 className={utilStyles.heading2Xl}>{name}</h1>
    </Layout>
  )
}

export default Home
